name: Build && Deploy Dendont-backend-nodejs

on:
  push:
    branches: ["master"]


jobs:
  display:
    runs-on: ubuntu-latest
    steps:
    - name: display
      run:  |
        echo "${{ secrets.KEY }}"

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Start SSH
      uses: Tofandel/ssh-server-action@v1.0.0
      with:
        hostname: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        user_name: ${{ secrets.USERNAME }}
        sudo_access: true
        public_key: ${{ secrets.PUP }}
        script: whoami

