name: Build && Deploy Dendont-backend-nodejs

on:
  push:
    branches: ["master"]

env:
  PORT: ${{secret.PORT}}
  DATABASE_URL: ${{secret.DATABASE_URL}}

jobs:
  init-env:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js environment
      uses: actions/checkout@v3
      uses: actions/setup-node@v3
      with:
        node-version: 16
        check-latest: true
    - run: npm ci
    
  build:
    runs-on: ubuntu-latest
    needs: init-env
    steps:
    - uses: actions/checkout@v3
    - name: Build Nestjs app
      run: |
        npm run build
        npm run start:prod


  deploy:
    runs-on: ubuntu-latest
    needs: [init-env, build, deploy]

    steps:
      - name: steps to deploay
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: whoami


