name: Build && Deploy Dendont-backend-nodejs

on:
  push:
    branches: ["master"]

env:
  PORT: ${{secrets.PORT}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}

jobs:
  init-env:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 16
        check-latest: true
    - run:  |
        npm ci
        npm run build


  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    needs: [init-env]

    steps:
      - uses: actions/checkout@v3
      - name: steps to deploay
        uses: appleboy/ssh-action@master
        with:
          host: 68.183.64.181
          username: root
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            echo "evn ${{ secrets.HOST }}"
            cd ~/nestjs
            npm ci
            pm2 start npm -- start



