name: Build && Deploy Dendont-backend-nodejs

on:
  push:
    branches: ["master"]

env:
  PORT: ${{secrets.PORT}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}

jobs:
  init-env:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 16
        check-latest: true
    - run: npm ci
    

  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    # needs: [init-env]

    steps:
      - name: steps to deploay
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script:  |
            whoami
