name: Build && Deploy Dendont-backend-nodejs

on:
  push:
    branches: ["master", "workflows"]

jobs:
  auto-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Run Lint && Prettier Formatter
      run: |
        npm i @typescript-eslint/eslint-plugin @typescript-eslint/parser
        npm i eslint eslint-config-prettier eslint-plugin-prettier prettier
        npm run lint
        npm run format

    - name: Commit & Push changes
      id: auto-commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply Lint&&Prettier Formatting

    - name: "Run if changes have been detected"
      if: steps.auto-commit.outputs.changes_detected == 'true'
      run: echo "Changes!"

    - name: "Run if no changes have been detected"
      if: steps.auto-commit.outputs.changes_detected == 'false'
      run: echo "No Changes!"


  init-env:
    runs-on: ubuntu-latest
    needs: [auto-format]

    steps:
    - uses: actions/checkout@master
    - name: Setup && Test Node.js environment
      uses: actions/setup-node@master
      with:
        node-version: 16
        check-latest: true
    - run: |
        npm ci
        npm run test:e2e

  deploy:
    runs-on: ubuntu-latest
    needs: [auto-format, init-env]

    steps:
      - name: steps to deploay
        uses: appleboy/ssh-action@master
        with:
          username: root
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          script:  |
            IFS='/'
            read -ra LOCAL_PATH <<< "${github.GITHUB_REPOSITORY}"
            if [ -d  "~/${LOCAL_PATH[1]}" ]
            then 
              cd "~/${LOCAL_PATH[1]}"
              git pull origin master
            else
              git clone https://github.com/El-khamisi/nestjs.git
              cd "~/${LOCAL_PATH[1]}"
            fi
            IFS=' '

            echo "
            PORT=${{secrets.PORT}}
            DATABASE_URL=${{secrets.DATABASE_URL}}
            SALT_ROUNDS=${{secrets.SALT_ROUNDS}}
            TOKEN_SECRET=${{secrets.TOKEN_SECRET}}
            TOKEN_SHORT_EXPIRY=${{secrets.TOKEN_SHORT_EXPIRY}}
            TOKEN_LONG_EXPIRY=${{secrets.TOKEN_LONG_EXPIRY}}
            "> .env
            pm2 del "${LOCAL_PATH[1]}"
            npm i --production 
            npm run build
            pm2 start "npm start" --name "${LOCAL_PATH[1]}"
            echo "### Hello "${LOCAL_PATH[1]}"! :rocket:" >> $GITHUB_STEP_SUMMARY
